services:
  # =============================================
  # NODE SERVER
  # =============================================
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react-internal-tools-management
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
